// <auto-generated />
using System;
using IngestionWorker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IngestionWorker.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20261001101642_InitialTelemetry")]
    partial class InitialTelemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IngestionWorker.Data.TelemetryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("PartCount")
                        .HasColumnType("bigint");

                    b.Property<double>("PowerKw")
                        .HasColumnType("double precision");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("SpindleLoadPct")
                        .HasColumnType("double precision");

                    b.Property<double>("SpindleSpeedRpm")
                        .HasColumnType("double precision");

                    b.Property<double>("SpindleTempC")
                        .HasColumnType("double precision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("VibrationMmS")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "Timestamp");

                    b.ToTable("telemetry", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
